version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: mcp_postgres
    environment:
      POSTGRES_USER: mcp_user
      POSTGRES_PASSWORD: mcp_password
      POSTGRES_DB: mcp_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6.0
    container_name: mcp_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mcp_user
      MONGO_INITDB_ROOT_PASSWORD: mcp_password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: